# Example Docker-Compose file
version: '3'
services:
  ttn-exporter:
    image: ghcr.io/opendata-heilbronn/ttn-gateway-exporter:v0.0.1
    ports:
      - "8080:8080"
    volumes:
      - ./targets-example.yaml:/etc/ttn-exporter/targets.yaml
